### ISSUE TITLE
Random crash while using -b and -s

### ISSUE THREAD

**Issue by pboardman** [stmcli/stmcli#7]
The bugs seems to happens randomly because running the same command again do not crash stmcli.

```
$ ./stmcli.py -b 150 -s 52150
Traceback (most recent call last):
  File "./stmcli.py", line 104, in <module>
    main()
  File "./stmcli.py", line 87, in main
    for i in next_departures:
TypeError: 'NoneType' object is not iterable

$ ./stmcli.py -b 150 -s 52150
14:01
14:05
14:09
14:12
14:15
14:19
14:24
14:29
14:33
14:37
```

**Comment by pboardman** [comment]
Done in pull request #11
