### ISSUE TITLE
Encoding error on printing result.

### ISSUE THREAD

**Issue by pboardman** [stmcli/stmcli#9]
## Direction 44-N

[Station Radisson Nord / Terminus] 59034
[Des Groseilliers / Davis] 53144
[Radisson / des Galeries-d'Anjou] 54653
[des Galeries d'Anjou / de la Malicorne] 54650
[des Galeries-d'Anjou / des Jalesnes] 54634
[des Galeries-d'Anjou / Beaubien] 54615
[des Galeries-d'Anjou / Saint-Zotique] 54602
Traceback (most recent call last):
  File "./stmcli.py", line 104, in <module>
    main()
  File "./stmcli.py", line 95, in main
    print(i)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 25: ordinal not in range(128)

**Comment by pboardman** [comment]
Done in #13
